version: '{branch}b{build}'

skip_non_tags: false

platform:
  - x64

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      CMAKE_OPTIONS: -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe
      MSVC_SETUP_PATH: C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat
      MSVC_SETUP_ARG: amd64
      CC: clang
      CXX: clang++
      PYTHON: "C:\\Python39-x64"

init:
  - git config --global core.autocrlf true

before_build:
  - cmake --version
  - clang-cl --version
  - if DEFINED MSVC_SETUP_PATH call "%MSVC_SETUP_PATH%" %MSVC_SETUP_ARG%
  - "%PYTHON%\\python.exe .\\Resources\\generate_translations.py"

build_script:
  - cmake -B build -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_PREFIX_PATH=C:\Qt\5.15\msvc2019_64
    -DCPACK_IFW_ROOT=E:/Qt/Tools/QtInstallerFramework -DCMAKE_RC_COMPILER=RC
  - cmake --build build --config Release --target PotatoAlert PotatoUpdater PotatoTest

after_build:
  - cd %APPVEYOR_BUILD_FOLDER%\build
  - mv updater\PotatoUpdater.exe .
  - 7z a PotatoAlert.zip -r .\PotatoAlert.exe .\PotatoUpdater.exe .\package\*

test_script:
  - cmd: cd %APPVEYOR_BUILD_FOLDER%\build\test
  - cmd: PotatoTest.exe

artifacts:
  - path: 'build\PotatoAlert.zip'
    name: 'potatoalert'

deploy:
  description: ''
  provider: GitHub
  auth_token:
    secure: yx3zdq/HfsztAvFdSyLIFxAXno5g1URqrLK1aiaeqgz9eY8NyOMG9SSLCNHSq93D
  artifact: potatoalert
  draft: true
  on:
    appveyor_repo_tag: true # deploy on tag push only
